- name: Find EC2 instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    aws_region: "us-east-1"
    ec2_tags:
      Project Code: "{{ mck_numbe }}"
     

  tasks:
    - name: Find EC2 Facts
      local_action:
        module: ec2_instance_facts
        region: "{{ aws_region }}"
        filters:
          "tag:Project Code": "mck-123456789"
      register: ec2_facts

    - debug:
        msg: "{{ ec2_facts.instances }}"

    - name: Terminate EC2 server
      local_action:
         module: ec2
         region: "{{ aws_region }}"
         instance_ids: "{{ item.instance_id }}"
         state: "absent"
         wait: True
      with_items: "{{ ec2_facts.instances }}"
